apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  security:
    dataPlane:
      mtls: true
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    openshiftRoute:
      enabled: false
    ingress:
      service:
        type: ClusterIP
        ports:
          - name: http2
            port: 9000
            targetPort: 9000
          - name: https
            port: 9443
            targetPort: 9443
