apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
  - name: primary
    route:
    - destination:
        host: hello
        port:
          number: 9000